$resolve.font=SF Pro Display|https://font.download/dl/font/sf-pro-display.zip

# BACKGROUND
background {
    monitor =
    path = /home/der_finn/.config/hypr/wallpapers/grove.png
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8916
    vibrancy = 0.8916
    vibrancy_darkness = 0.0
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = 
    font_size = 60
    font_family = SF Pro Display Bold
    position = 30, -8
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = 
    font_size = 19
    font_family = SF Pro Display Bold
    position = 35, -60
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 320, 55
    color = 
    rounding = -1
    border_size = 0
    border_color =
    rotate = 0
    xray = false # if true, make a "hole" in the background (rectangle of specified size, no rotation)

    position = 34, -190
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text =     $USER
    color = 
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    font_size = 16
    font_family = SF Pro Display Bold
    position = 38, -190
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(255, 255, 255, 0)
    inner_color =
    font_color = 
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <i><span>    Enter Pass</span></i>
    hide_input = false
    position = 34, -268
    halign = center
    valign = center
    check_color =
    fail_color = rgb(204, 34, 34) # if authentication failed, changes outer_color and fail message color
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i> # can be set to empty
    fail_transition = 300 # transition time in ms between normal outer_color and fail_color

}
