# gruvbox palette
$bg = rgb(282828)
$fg = rgb(ebdbb2)
$gray = rgb(928374)
$red = rgb(cc241d)
$green = rgb(98971a)
$yellow = rgb(d79921)
$blue = rgb(458588)
$purple = rgb(b16286)
$aqua = rgb(689d6a)
$orange = rgb(d65d0e)

background {
    monitor =
    path = /home/$USER/.config/hypr/wallpapers/grove.png
    blur_size = 3
    blur_passes = 3
    contrast = 1.3
    brightness = 0.8916
    vibrancy = 0.2696
    vibrancy_darkness = 0.05
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# time
label {
    monitor =
    text = cmd[update:1000] echo "<span>$TIME</span>"
    color = $fg
    font_size = 60
    font_family = DepartureMono Nerd Font
    position = 30, 0
    halign = center
    valign = center
}

# date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = $fg
    font_size = 20
    font_family = DepartureMono Nerd Font
    position = 35, -60
    halign = center
    valign = center
}

# username-box
shape {
    monitor =
    size = 320, 55
    color = $bg
    rounding = 12
    border_size = 2
    border_color = $gray
    rotate = 0
    position = 34, -190
    halign = center
    valign = center
}

# username
label {
    monitor =
    text =     $USER
    color = $aqua
    outline_thickness = 2
    font_size = 16
    font_family = DepartureMono Nerd Font
    position = 38, -190
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 320, 55
    outline_thickness = 2
    outer_color = $gray
    dots_size = 0.2
    dots_spacing = 0.5
    dots_center = true
    inner_color = $bg
    font_color = $aqua
    fade_on_empty = false
    rounding = 12
    border_size = 2
    border_color = $gray
    font_family = DepartureMono Nerd Font
    placeholder_text = <i><span>    Enter Pass</span></i>
    hide_input = false
    position = 34, -268
    halign = center
    valign = center
    check_color = $red
    fail_color = $red # if authentication failed, changes outer_color and fail message color
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300 # transition time in ms between normal outer_color and fail_color
}
